--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/SellMe
build-by-default: true
branches:
- main
projects:
  SellMe:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.0.1
      - src: jojoe77777/FormAPI/libFormAPI
          version: ^2.1.0
...
