name: SellMe
author: cosmicnebula200
api: 4.0.0
main: cosmicnebula200\SellMe\SellMe
version: 1.0.0

permissions:
  sellme.command.sell:
    default: true
    description: with this permission the player can use the sell command
  sellme.subcommand.hand:
    default: true
    description: with this permission the player sell his/her hand
  sellme.subcommand.all:
    default: true
    description: with this permission the player sell all items in his/her inv which are similar to his current item in hand
  sellme.subcommand.inv:
    default: true
    description: with this permission the player can sell his/her inventory
  sellme.command.autosell:
    default: true
    description: with this permission the player can toggle his autosell status